server:
  port: 8080

spring:
  application:
    name: sentiment-check-with-ai
  config:
    import: file:.env.properties
  data:
    redis:
      host: localhost  # Хост Redis
      port: 6379       # Порт Redis
      timeout: 2000ms  # Таймаут подключения
      lettuce:
        pool:
          max-active: 10   # Максимум соединений в пуле
          max-idle: 5      # Максимум idle соединений
          min-idle: 2      # Минимум idle соединений
      cache:
        timeToLive: 24
      dataPrefix: "sentiment:data:"
      textPrefix: "sentiment:text:"

sentiment:
  ai:
    default-strategy: huggingface  # default strategy
    huggingface:
      api-key: ${HUGGINGFACE_API_KEY}
      model: distilbert-base-uncased-finetuned-sst-2-english
      api-url: https://api-inference.huggingface.co/models/

logging:
  level:
    com.sentiment: DEBUG  # Логи нашего приложения
    org.springframework.data.redis: INFO  # Логи Redis

#redis:
#  keys:
#    sentimentLog:
#      timeToLive: PT5M